spring.application.name=ecom-search-service
spring.data.mongodb.uri=mongodb+srv://deewanmewada81:Deewan12345@cluster0.xajvv.mongodb.net/ecommerce_search?retryWrites=true&w=majority&appName=Cluster0


# Redis / Upstash
spring.data.redis.host=enabled-seagull-170969.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAApvZAAIgcDIyNTFmYjg5MGUzYzU0MWZhOWYxY2MwODg1NDk0NTljNQ
spring.data.redis.ssl.enabled=true


# log patter for distibuted service
logging.pattern.level=%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]
