spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/5th_jan_2026_batch
    username: root
    password: Deewan62@61
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081